coverage:
  range: 50..90
  round: down
  precision: 2

  ignore:
    - "projects"
    - "examples"
    - "test"
    - "src/Grids"
    - "src/Models"
    - "src/Observations"
    - "src/ParameterEstimation"

  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 20%

comment: false

github_checks:
    annotations: false
